### ISSUE TITLE
How to enable/capture external service

### ISSUE THREAD

**Issue by sahilpaudel-pe** [newrelic/node-newrelic-koa#106]
Below is my app.js

```
require('@newrelic/koa');
import Koa from 'koa';
import koaBody from 'koa-body';
```

newrelic.js

```
'use strict'
/**
 * New Relic agent configuration.
 *
 * See lib/config/default.js in the agent distribution for a more complete
 * description of configuration variables and their potential values.
 */
exports.config = {
  /**
   * Array of application names.
   */
  app_name    : [process.env.NEW_RELIC_APP_NAME],
  /**
   * Your New Relic license key.
   */
  license_key : process.env.NODE_ENV == 'production' ? process.env.NEW_RELIC_LICENSE_KEY : process.env.NEW_RELIC_LICENSE_KEY,
  logging: {
    /**
     * Level at which to log. 'trace' is most useful to New Relic when diagnosing
     * issues with the agent, 'info' and higher will impose the least overhead on
     * production applications.
     */
    level: 'info'
  },
  /**
   * When true, all request headers except for those listed in attributes.exclude
   * will be captured for all traces, unless otherwise specified in a destination's
   * attributes include/exclude lists.
   */
  allow_all_headers: true,
  enforce_backstop: false,
  distributed_tracing: {
    enabled: true
  },
  attributes: {
    /**
     * Prefix of attributes to exclude from all destinations. Allows * as wildcard
     * at end.
     *
     * NOTE: If excluding headers, they must be in camelCase form to be filtered.
     *
     * @env NEW_RELIC_ATTRIBUTES_EXCLUDE
     */
    exclude: [
      'request.headers.cookie',
      'request.headers.authorization',
      'request.headers.proxyAuthorization',
      'request.headers.setCookie*',
      'request.headers.x*',
      'response.headers.cookie',
      'response.headers.authorization',
      'response.headers.proxyAuthorization',
      'response.headers.setCookie*',
      'response.headers.x*'
    ]
  }
}
```
I am not getting the external service metrics, can you please point me to the right direction, I tried reading the docs too, but couldn't find anything or understand.

**Comment by michaelgoin** [comment]
Hi @sahilpaudel-pe,

For issues like this, I'd reach out to our support team over at support.newrelic.com. That is where we do more in-depth troubleshooting, including gathering sensitive information such as logs, etc. to run down these sorts of issues.

For external metrics, we collect those by default without needing any special configuration. We should capture pretty much anything built on the `http` and `https` core modules. We won't yet capture anything http2 or grpc related. We also won't capture `undici` by default. For `undici` we do have experimental instrumentation behind a feature flag.

Assuming you are using something built on `http` or `https` such as `request`, `axios`, etc. for your external web calls, the problem could be that your application has some state loss due to a dependency in the call chain we don't instrument or failure to load the agent early enough. Tools such as `webpack` can cause problems here. If you are confident `newrelic` is the first module loaded in your application, then I'd definitely go the support route so we can dig into some trace level logs, code snippets and what dependencies are in play besides koa (or if say a newer version of something like koa-body is causing issues).

One thing worth noting, we automatically bundle `@newrelic/koa` in the Node.js agent, so you don't need to manually import unless you need to be on a major version we've yet to upgrade in the agent. The agent is currently up to date, so I'd recommend instead having installed the `newrelic` package and using either `node -r newrelic <your entry point>` to launch your app (recommended) or having `require('newrelic')` as the first line in your application. You won't need the `@newrelic/koa` package manually installed in this case as it is bundled in the agent.
